# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PlotterGUI.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(582, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("plotterIcon-1.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.NodeObj_GB = QtWidgets.QGroupBox(self.centralwidget)
        self.NodeObj_GB.setGeometry(QtCore.QRect(220, 10, 331, 431))
        self.NodeObj_GB.setObjectName("NodeObj_GB")
        self.Node_TE = QtWidgets.QTextEdit(self.NodeObj_GB)
        self.Node_TE.setGeometry(QtCore.QRect(10, 40, 151, 351))
        self.Node_TE.setReadOnly(True)
        self.Node_TE.setObjectName("Node_TE")
        self.label = QtWidgets.QLabel(self.NodeObj_GB)
        self.label.setGeometry(QtCore.QRect(20, 20, 71, 16))
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.NodeObj_GB)
        self.frame.setGeometry(QtCore.QRect(170, 40, 151, 91))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.NodeDel_PB = QtWidgets.QPushButton(self.frame)
        self.NodeDel_PB.setGeometry(QtCore.QRect(20, 50, 75, 23))
        self.NodeDel_PB.setObjectName("NodeDel_PB")
        self.NodeMove_PB = QtWidgets.QPushButton(self.frame)
        self.NodeMove_PB.setGeometry(QtCore.QRect(20, 20, 75, 23))
        self.NodeMove_PB.setAutoFillBackground(True)
        self.NodeMove_PB.setCheckable(True)
        self.NodeMove_PB.setObjectName("NodeMove_PB")
        self.label_2 = QtWidgets.QLabel(self.NodeObj_GB)
        self.label_2.setGeometry(QtCore.QRect(180, 20, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.NodeObj_GB)
        self.label_3.setGeometry(QtCore.QRect(180, 140, 91, 16))
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setObjectName("label_3")
        self.frame_2 = QtWidgets.QFrame(self.NodeObj_GB)
        self.frame_2.setGeometry(QtCore.QRect(169, 160, 151, 231))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.BW_HS = QtWidgets.QSlider(self.frame_2)
        self.BW_HS.setGeometry(QtCore.QRect(10, 80, 131, 21))
        self.BW_HS.setMaximum(5)
        self.BW_HS.setProperty("value", 2)
        self.BW_HS.setOrientation(QtCore.Qt.Horizontal)
        self.BW_HS.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.BW_HS.setObjectName("BW_HS")
        self.NodeBW_L = QtWidgets.QLabel(self.frame_2)
        self.NodeBW_L.setGeometry(QtCore.QRect(50, 60, 41, 16))
        self.NodeBW_L.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.NodeBW_L.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.NodeBW_L.setObjectName("NodeBW_L")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 31, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 31, 16))
        self.label_5.setObjectName("label_5")
        self.NodeFreq_L = QtWidgets.QLabel(self.frame_2)
        self.NodeFreq_L.setGeometry(QtCore.QRect(50, 10, 41, 16))
        self.NodeFreq_L.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.NodeFreq_L.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.NodeFreq_L.setObjectName("NodeFreq_L")
        self.Freq_HS = QtWidgets.QSlider(self.frame_2)
        self.Freq_HS.setGeometry(QtCore.QRect(10, 30, 131, 21))
        self.Freq_HS.setAutoFillBackground(False)
        self.Freq_HS.setMaximum(20)
        self.Freq_HS.setProperty("value", 11)
        self.Freq_HS.setOrientation(QtCore.Qt.Horizontal)
        self.Freq_HS.setInvertedAppearance(False)
        self.Freq_HS.setInvertedControls(False)
        self.Freq_HS.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.Freq_HS.setTickInterval(0)
        self.Freq_HS.setObjectName("Freq_HS")
        self.NodeUpdate_PB = QtWidgets.QPushButton(self.frame_2)
        self.NodeUpdate_PB.setGeometry(QtCore.QRect(10, 180, 75, 23))
        self.NodeUpdate_PB.setObjectName("NodeUpdate_PB")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(10, 140, 31, 16))
        self.label_6.setObjectName("label_6")
        self.NodeCID_LE = QtWidgets.QLineEdit(self.frame_2)
        self.NodeCID_LE.setGeometry(QtCore.QRect(60, 140, 41, 16))
        self.NodeCID_LE.setText("")
        self.NodeCID_LE.setObjectName("NodeCID_LE")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(100, 10, 31, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(100, 60, 31, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(10, 110, 51, 16))
        self.label_9.setObjectName("label_9")
        self.NodeTXP_LE = QtWidgets.QLineEdit(self.frame_2)
        self.NodeTXP_LE.setGeometry(QtCore.QRect(60, 110, 41, 16))
        self.NodeTXP_LE.setObjectName("NodeTXP_LE")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(110, 110, 31, 16))
        self.label_10.setObjectName("label_10")
        self.ControlPanel_GB = QtWidgets.QGroupBox(self.centralwidget)
        self.ControlPanel_GB.setGeometry(QtCore.QRect(10, 10, 201, 431))
        self.ControlPanel_GB.setObjectName("ControlPanel_GB")
        self.Simulation_PB = QtWidgets.QPushButton(self.ControlPanel_GB)
        self.Simulation_PB.setGeometry(QtCore.QRect(10, 40, 91, 23))
        self.Simulation_PB.setObjectName("Simulation_PB")
        self.StopSimulation_PB = QtWidgets.QPushButton(self.ControlPanel_GB)
        self.StopSimulation_PB.setGeometry(QtCore.QRect(10, 70, 91, 23))
        self.StopSimulation_PB.setObjectName("StopSimulation_PB")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(20, 490, 131, 51))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        self.label_11.setGeometry(QtCore.QRect(10, 0, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_11.setFont(font)
        self.label_11.setTextFormat(QtCore.Qt.RichText)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        self.label_12.setGeometry(QtCore.QRect(10, 20, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_12.setFont(font)
        self.label_12.setTextFormat(QtCore.Qt.RichText)
        self.label_12.setObjectName("label_12")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 582, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuNew = QtWidgets.QMenu(self.menuFile)
        self.menuNew.setObjectName("menuNew")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionPlot = QtWidgets.QAction(MainWindow)
        self.actionPlot.setObjectName("actionPlot")
        self.actiongtgtgt = QtWidgets.QAction(MainWindow)
        self.actiongtgtgt.setObjectName("actiongtgtgt")
        self.actionRandom_Nodes = QtWidgets.QAction(MainWindow)
        self.actionRandom_Nodes.setObjectName("actionRandom_Nodes")
        self.actiond = QtWidgets.QAction(MainWindow)
        self.actiond.setObjectName("actiond")
        self.actionXmlPlot = QtWidgets.QAction(MainWindow)
        self.actionXmlPlot.setObjectName("actionXmlPlot")
        self.actionRandomPlot = QtWidgets.QAction(MainWindow)
        self.actionRandomPlot.setObjectName("actionRandomPlot")
        self.actionManualPlot = QtWidgets.QAction(MainWindow)
        self.actionManualPlot.setObjectName("actionManualPlot")
        self.menuNew.addAction(self.actionXmlPlot)
        self.menuNew.addAction(self.actionRandomPlot)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuNew.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "P2MP Plotter GUI"))
        self.NodeObj_GB.setTitle(_translate("MainWindow", "Node Object"))
        self.Node_TE.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Node Details"))
        self.NodeDel_PB.setText(_translate("MainWindow", "Delete Object"))
        self.NodeMove_PB.setText(_translate("MainWindow", "Move Object"))
        self.label_2.setText(_translate("MainWindow", "Node Control"))
        self.label_3.setText(_translate("MainWindow", "Node Parameters"))
        self.NodeBW_L.setText(_translate("MainWindow", "5"))
        self.label_4.setText(_translate("MainWindow", "Freq.:"))
        self.label_5.setText(_translate("MainWindow", "BW:"))
        self.NodeFreq_L.setText(_translate("MainWindow", "2100"))
        self.NodeUpdate_PB.setText(_translate("MainWindow", "Update Node"))
        self.label_6.setText(_translate("MainWindow", "CID:"))
        self.label_7.setText(_translate("MainWindow", "MHz"))
        self.label_8.setText(_translate("MainWindow", "MHz"))
        self.label_9.setText(_translate("MainWindow", "TX PWR:"))
        self.NodeTXP_LE.setText(_translate("MainWindow", "26"))
        self.label_10.setText(_translate("MainWindow", "dBm"))
        self.ControlPanel_GB.setTitle(_translate("MainWindow", "Control Panel"))
        self.Simulation_PB.setText(_translate("MainWindow", "Start Simulation"))
        self.StopSimulation_PB.setText(_translate("MainWindow", "Stop Simulation"))
        self.label_11.setText(_translate("MainWindow", "© Ohad Shpindel"))
        self.label_12.setText(_translate("MainWindow", "Version 1.1"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuNew.setTitle(_translate("MainWindow", "New Plot"))
        self.actionPlot.setText(_translate("MainWindow", "Plot"))
        self.actiongtgtgt.setText(_translate("MainWindow", "gtgtgt"))
        self.actionRandom_Nodes.setText(_translate("MainWindow", "Random Nodes"))
        self.actiond.setText(_translate("MainWindow", "Load from XML file"))
        self.actionXmlPlot.setText(_translate("MainWindow", "Load from XML file"))
        self.actionRandomPlot.setText(_translate("MainWindow", "Random Nodes"))
        self.actionManualPlot.setText(_translate("MainWindow", "Manual Nodes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

